SELECT 
    MONTH(START_DATE) AS MONTH, 
    C1.CAR_ID, 
    COUNT(C1.CAR_ID) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C1 
INNER JOIN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID HAVING COUNT(HISTORY_ID) >= 5
) AS C2
ON 
    C1.CAR_ID = C2.CAR_ID
WHERE 
    C1.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    MONTH, C1.CAR_ID
HAVING 
    RECORDS > 0
ORDER BY
    MONTH, C1.CAR_ID DESC;