SELECT C.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
WHERE C.CAR_ID = CH.CAR_ID 
    AND START_DATE LIKE '%-10-%'
    AND CAR_TYPE = '세단'
GROUP BY C.CAR_ID 
ORDER BY C.CAR_ID DESC