SELECT COUNT(F1.ID) AS FISH_COUNT, MAX(L) AS MAX_LENGTH, F1.FISH_TYPE
FROM FISH_INFO AS F1
INNER JOIN (
    SELECT ID, FISH_TYPE, 
        (
            CASE 
            WHEN LENGTH IS NULL OR LENGTH < 10 THEN 10
            ELSE LENGTH 
            END
        ) AS L
    FROM FISH_INFO
) AS F2 ON F1.ID = F2.ID
GROUP BY F1.FISH_TYPE HAVING AVG(L) >= 33
ORDER BY FISH_TYPE